### ISSUE TITLE
run benchmark from cli is not working

### ISSUE THREAD

**Issue by prekucki** [golemfactory/golem-client#27]
./golemcli.py envs recount BLENDER
RPC: call error: <twisted.python.failure.Failure autobahn.wamp.exception.ApplicationError: ApplicationError(error=<wamp.error.runtime_error>, args=['expected str, bytes or os.PathLike object, not NoneType'], kwargs={}, enc_algo=None)> 
[10:01:12.117877] ERROR: Exception: ApplicationError(error=<wamp.error.runtime_error>, args=['expected str, bytes or os.PathLike object, not NoneType'], kwargs={}, enc_algo=None)

**Comment by kubkon** [comment]
Hmm, this one seems to work fine with my install on Ubuntu (latest [golem-develop](https://github.com/golemfactory/golem/tree/develop)):

```
golem-client ) ./target/debug/golemcli envs recount BLENDER
---
1144.1168796200985
golem-client ) ./target/release/golemcli envs recount BLENDER
---
1139.5707221648646
golem-client ) ./target/debug/golemcli envs recount WASM
---
943.3788779418287
golem-client ) ./target/release/golemcli envs recount WASM
---
857.1818622510082
```

**Comment by weaselix** [comment]
It works actually now.

` ./golemcli.py envs recount BLENDER
1089.4254686621932
`
