### ISSUE TITLE
Choose Use Case (Application) for API demo

### ISSUE THREAD

**Issue by prekucki** [golemfactory/golem-client#36]
+ Try to do Demand/offer spec for example Application current standars.

**Comment by kubkon** [comment]
So it seems that the best (initial) use case for our MarketAPI and related endeavour will be "Transcoding" as we already do possess some knowledge about it, and hence, we can focus on the API itself rather than the use case.

**Comment by kubkon** [comment]
Transcoding it is then. Closing!
